In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('../data/cs-training.csv')

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nFirst 5 rows:")
df.head()

Dataset shape: (150000, 12)

Columns:
['Unnamed: 0', 'SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age', 'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome', 'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfDependents']

Data types:
Unnamed: 0                                int64
SeriousDlqin2yrs                          int64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
dtype: object

First 5 rows:

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [2]:
print("Null values per column:")
print(df.isnull().sum())

print("\nNull values percentage:")
print((df.isnull().sum() / len(df) * 100).round(2))

Null values per column:
Unnamed: 0                                  0
SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

Null values percentage:
Unnamed: 0                               0.00
SeriousDlqin2yrs                         0.00
RevolvingUtilizationOfUnsecuredLines     0.00
age                                      0.00
NumberOfTime30-59DaysPastDueNotWorse     0.00
DebtRatio                                0.00
MonthlyIncome                           19.82
NumberOfOpenCreditLinesAndLoans          0.00
NumberOfTimes90DaysLate                  0.00
NumberRealEstateLoansOrLines             0.00
NumberOfTime60-89DaysPastDueNotWorse     0.00
NumberOfDependents                       2.62
dtype: float64

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../data/cs-training.csv')
print("Shape:" , df.shape)
df.head()

Shape: (150000, 12)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [11]:
col_info = {
    'SeriousDlqin2yrs': 'TARGET — 1 = defaulted, 0 = did not default',
    'RevolvingUtilizationOfUnsecuredLines': 'Credit card usage ratio (0 to 1)',
    'age': 'Customer age in years',
    'NumberOfTime30-59DaysPastDueNotWorse': 'Times payment was 30-59 days late',
    'DebtRatio': 'Monthly debt payments / Monthly income',
    'MonthlyIncome': 'Monthly income in USD',
    'NumberOfOpenCreditLinesAndLoans': 'Total open loans and credit lines',
    'NumberOfTimes90DaysLate': 'Times payment was 90+ days late',
    'NumberRealEstateLoansOrLines': 'Number of property/mortgage loans',
    'NumberOfTime60-89DaysPastDueNotWorse': 'Times payment was 60-89 days late',
    'NumberOfDependents': 'Number of dependents excluding self'
}

for col, meaning in col_info.items():
    print(f"{col:45} -> {meaning}")

SeriousDlqin2yrs                              -> TARGET — 1 = defaulted, 0 = did not default
RevolvingUtilizationOfUnsecuredLines          -> Credit card usage ratio (0 to 1)
age                                           -> Customer age in years
NumberOfTime30-59DaysPastDueNotWorse          -> Times payment was 30-59 days late
DebtRatio                                     -> Monthly debt payments / Monthly income
MonthlyIncome                                 -> Monthly income in USD
NumberOfOpenCreditLinesAndLoans               -> Total open loans and credit lines
NumberOfTimes90DaysLate                       -> Times payment was 90+ days late
NumberRealEstateLoansOrLines                  -> Number of property/mortgage loans
NumberOfTime60-89DaysPastDueNotWorse          -> Times payment was 60-89 days late
NumberOfDependents                            -> Number of dependents excluding self

In [5]:
print("Missing values before cleaning: ")
print(df.isnull().sum())
print("\nMissing percentange: ")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing values before cleaning:
Unnamed: 0                                  0
SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

Missing percentange:
Unnamed: 0                               0.00
SeriousDlqin2yrs                         0.00
RevolvingUtilizationOfUnsecuredLines     0.00
age                                      0.00
NumberOfTime30-59DaysPastDueNotWorse     0.00
DebtRatio                                0.00
MonthlyIncome                           19.82
NumberOfOpenCreditLinesAndLoans          0.00
NumberOfTimes90DaysLate                  0.00
NumberRealEstateLoansOrLines             0.00
NumberOfTime60-89DaysPastDueNotWorse     0.00
NumberOfDependents                       2.62
dtype: float64

In [13]:
#fill with median
df['MonthlyIncome'] = df['MonthlyIncome'].fillna(df['MonthlyIncome'].median())
#fill with 0
df['NumberOfDependents'] = df['NumberOfDependents'].fillna(0)

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Unnamed: 0                              0
SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

In [14]:
#removing outliers
print("Shape before removing outliers:", df.shape)
df = df[(df['age'] > 18) & (df['age'] < 100)]
df = df[df['MonthlyIncome'] < 500000]
df = df[df['DebtRatio'] < 5]

print("Shape after removing outliers:", df.shape)

Shape before removing outliers: (120191, 12)
Shape after removing outliers: (120191, 12)

In [21]:
#Feature Engineering
df['age_group'] = pd.cut(df['age'],
                         bins = [18, 30, 45, 60, 100],
                         labels = ['Young', 'Middle', 'Senior', 'Old'])
df['income_tier'] = pd.cut(df['MonthlyIncome'],
                           bins = [0, 3000, 7000, 15000, 50000],
                           labels = ['Low', 'Medium', 'High', 'Very High'])
df['debt_tier'] = pd.cut(df['DebtRatio'],
                         bins = [0, 0.3, 0.6, 1, 5],
                         labels = ['Low Risk', 'Medium Risk', 'High Risk', 'Very High Risk'])
print("New Columns Created Successfully!")
print(df[['age_group', 'income_tier', 'debt_tier']].head(10))

New Columns Created Successfully!
   age_group income_tier    debt_tier
0     Middle        High    High Risk
1     Middle         Low     Low Risk
2     Middle      Medium     Low Risk
3      Young      Medium     Low Risk
4     Senior         NaN     Low Risk
5        Old      Medium  Medium Risk
7     Middle      Medium     Low Risk
9     Senior   Very High    High Risk
10     Young         Low  Medium Risk
11    Senior      Medium  Medium Risk